services:
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finnisimo
      POSTGRES_PASSWORD: Finndavid1
      POSTGRES_DB: finnisimolibrary
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
